// Generates road-snapped patrol routes for each motorcycle using OSRM (OpenStreetMap
// routing). Waypoints are placed on the Manado street grid (on land); OSRM snaps them
// to the nearest roads and returns a street-following geometry. Output is baked into
// src/data/routes.generated.ts so the app needs no runtime network calls.
import { writeFileSync } from 'node:fs'

const OSRM = 'https://router.project-osrm.org'
const round = (v) => Math.round(v * 1e5) / 1e5
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

// Operational geofence (lng,lat) — for validation only.
const ZONE = [
  [124.825, 1.518], [124.865, 1.521], [124.888, 1.496], [124.87, 1.46],
  [124.825, 1.438], [124.805, 1.452], [124.806, 1.49], [124.825, 1.518],
]
function inPoly([x, y], poly) {
  let inside = false
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [ax, ay] = poly[i], [bx, by] = poly[j]
    if (ay > y !== by > y) {
      const xc = ((bx - ax) * (y - ay)) / (by - ay) + ax
      if (x < xc) inside = !inside
    }
  }
  return inside
}

// Patrol loops as [lng,lat] waypoints (on land, on the city road grid).
const LOOPS = {
  'MOTOR-001': [[124.8432, 1.4870], [124.8448, 1.4925], [124.8462, 1.4958], [124.8505, 1.4948], [124.8492, 1.4902], [124.8456, 1.4876]],
  'MOTOR-002': [[124.8442, 1.4885], [124.8478, 1.4930], [124.8522, 1.4960], [124.8542, 1.4925], [124.8502, 1.4890], [124.8462, 1.4872]],
  'MOTOR-003': [[124.8520, 1.4960], [124.8560, 1.4985], [124.8582, 1.5008], [124.8542, 1.5004], [124.8512, 1.4980]],
  'MOTOR-004': [[124.8432, 1.4862], [124.8462, 1.4842], [124.8492, 1.4856], [124.8482, 1.4886], [124.8446, 1.4880]],
  'MOTOR-008': [[124.8452, 1.4880], [124.8472, 1.4940], [124.8522, 1.4975], [124.8562, 1.4950], [124.8522, 1.4900], [124.8472, 1.4875]],
  // MOTOR-009 patrols the Malalayang coastal road — OUTSIDE the zone (geofence violation).
  'MOTOR-009': [[124.7960, 1.4455], [124.7985, 1.4425], [124.8005, 1.4400], [124.8015, 1.4435], [124.7985, 1.4460]],
}

// Stationary units (available/maintenance) — snap these to the nearest road.
const STATIC = {
  'MOTOR-005': [124.8420, 1.4948], // Megamas (boulevard, inland)
  'MOTOR-006': [124.8430, 1.5050], // Pelabuhan Manado (port access road)
  'MOTOR-007': [124.8444, 1.4842], // Pasar 45
  'MOTOR-010': [124.8534, 1.4982], // Bengkel Mitra, Tikala
}

async function fetchRoute(wps) {
  const closed = [...wps, wps[0]]
  const coords = closed.map(([lng, lat]) => `${lng},${lat}`).join(';')
  const url = `${OSRM}/route/v1/driving/${coords}?overview=full&geometries=geojson&continue_straight=false`
  const res = await fetch(url, { signal: AbortSignal.timeout(30000) })
  const j = await res.json()
  if (j.code !== 'Ok') throw new Error('route ' + j.code)
  // dedupe near-identical consecutive points, store as [lat,lng]
  const raw = j.routes[0].geometry.coordinates
  const out = []
  for (const [lng, lat] of raw) {
    const p = [round(lat), round(lng)]
    const last = out[out.length - 1]
    if (!last || Math.abs(last[0] - p[0]) > 1e-5 || Math.abs(last[1] - p[1]) > 1e-5) out.push(p)
  }
  return out
}

async function fetchNearest(lng, lat) {
  const url = `${OSRM}/nearest/v1/driving/${lng},${lat}`
  const res = await fetch(url, { signal: AbortSignal.timeout(20000) })
  const j = await res.json()
  if (j.code !== 'Ok') return [round(lat), round(lng)]
  const [nlng, nlat] = j.waypoints[0].location
  return [round(nlat), round(nlng)]
}

const routes = {}
const positions = {}

for (const [id, wps] of Object.entries(LOOPS)) {
  try {
    const geom = await fetchRoute(wps)
    routes[id] = geom
    positions[id] = geom[0]
    const insideFrac = geom.filter(([lat, lng]) => inPoly([lng, lat], ZONE)).length / geom.length
    console.log(`${id}: ${geom.length} pts · inside-zone ${(insideFrac * 100).toFixed(0)}%`)
    await sleep(400)
  } catch (e) {
    console.log(`${id}: FAILED (${e.message}) — keeping hand route`)
  }
}

for (const [id, [lng, lat]] of Object.entries(STATIC)) {
  try {
    positions[id] = await fetchNearest(lng, lat)
    console.log(`${id}: snapped → ${positions[id].join(', ')}`)
    await sleep(300)
  } catch (e) {
    positions[id] = [round(lat), round(lng)]
    console.log(`${id}: nearest FAILED (${e.message})`)
  }
}

const banner = `// AUTO-GENERATED by scripts/gen-routes.mjs — DO NOT EDIT BY HAND.
// Road-snapped patrol routes & positions for Kota Manado (OSRM / OpenStreetMap).
import type { LatLng } from '../types'
`
const body =
  `\nexport const GEN_ROUTES = ${JSON.stringify(routes)} as Record<string, LatLng[]>\n` +
  `\nexport const GEN_POS = ${JSON.stringify(positions)} as Record<string, LatLng>\n`

writeFileSync('src/data/routes.generated.ts', banner + body)
console.log('\n✓ wrote src/data/routes.generated.ts')
